ENV:
  data_path: ./data/DADA-2000
  batch_size: 1
  image_shape: [660, 1584]
  input_shape: [480, 640]
  frame_interval: 5
  max_frames: -1
  binary_cls: true
  num_workers: 0
  dim_state: 128
  dim_action: 4
  env_model: ./output/saliency/checkpoints/saliency_model_25.pth
SAC:
  gamma: 0.99
  tau: 1.0
  lr: 0.0003
  num_classes: 2
  hidden_size: 256
  policy: "Deterministic"
  target_update_interval: 1000
  automatic_entropy_tuning: False
  alpha: 0.05
  beta: 0.01
  replay_size: 1000000
  batch_size: 512
  updates_per_step: 1
