ENV:
  data_path: ./data/DADA-2000-small
  batch_size: 5
  image_shape: [330, 792]
  input_shape: [480, 640]
  frame_interval: 5
  step_size: 1
  len_clip: 1
  num_workers: 4
  rho: 0.5
  fusion: "static"  # static or dynamic
  fusion_margin: 0.8
  score_thresh: 0.5
  use_salmap: false  # set to False to speedup data loading
  state_norm: true
  saliency: 'MLNet'
  env_model: ./models/saliency/mlnet_25.pth
SAC:
  gamma: 0.99
  tau: 0.005
  lr: 0.0003
  num_classes: 2
  hidden_size: 64
  dim_state: 128
  dim_action_acc: 1
  dim_action_fix: 2
  type_acc: "Gaussian"
  type_fix: "Gaussian"
  target_update_interval: 1
  automatic_entropy_tuning: true
  alpha: 0.001
  beta_accident: 1.0
  beta_fixation: 10.0
  replay_size: 1000000
  batch_size: 64
  updates_per_step: 1
  logging_interval: 100
  weight_decay: 0.00001
  arch_type: "mlp"  # mlp or rae
  dim_latent: 64    # only useful when rae
  latent_lambda: 0.0001
  gpu_replay: true
