ENV:
  data_path: ./data/DADA-2000-small
  batch_size: 4
  image_shape: [330, 792]
  input_shape: [480, 640]
  mask_shape: [5, 12]
  frame_interval: 5
  step_size: 1
  len_clip: 1
  num_workers: 2
  score_thresh: 0.7
  use_salmap: false  # set to False to speedup data loading
  state_norm: true
  saliency: 'MLNet'
  env_model: ./models/saliency/mlnet_25.pth
SAC:
  gamma: 0.99
  tau: 0.005
  lr: 0.0003
  num_classes: 2
  hidden_size: 64
  dim_state_fovea: 64
  dim_state_contex: 64
  dim_state_atten: 60  # 5 x 12
  dim_action_accident: 1
  dim_action_attention: 60
  policy: "Gaussian"
  target_update_interval: 1000
  automatic_entropy_tuning: true
  alpha: 0.001
  beta_actor: 0.01
  beta_fix: 1.0
  replay_size: 1000000
  batch_size: 64
  updates_per_step: 1
  logging_interval: 100
  weight_decay: 0.00001
  arch_type: "rae"  # mlp or rae
  dim_latent: 64    # only useful when rae
  latent_lambda: 0.0001
  gpu_replay: true
