ENV:
  data_path: ./data/DADA-2000
  batch_size: 1
  image_shape: [660, 1584]
  input_shape: [480, 640]
  frame_interval: 5
  step_size: 1
  len_clip: 1
  max_frames: 120    # 600/5, 20 seconds
  binary_cls: true
  num_workers: 2
  dim_state: 128
  dim_action: 3
  score_thresh: 0.7
  use_salmap: false  # set to False to speedup data loading
  use_foveation: true
  state_norm: true
  saliency: 'MLNet'
  env_model: ./models/saliency/mlnet_25.pth
SAC:
  gamma: 0.99
  tau: 0.005
  lr: 0.0003
  num_classes: 2
  hidden_size: 64
  policy: "Gaussian"
  target_update_interval: 1000
  automatic_entropy_tuning: true
  alpha: 0.001
  beta_actor: 0.01
  beta_fix: 1.0
  replay_size: 1000000
  batch_size: 256
  updates_per_step: 4
  logging_interval: 100
  weight_decay: 0.0005
  arch_type: "rae"  # mlp or rae
  dim_latent: 64    # only useful when rae
  latent_lambda: 0.0001
  gpu_replay: true
