ENV:
  data_path: ./data/DADA-2000
  batch_size: 1
  image_shape: [660, 1584]
  input_shape: [480, 640]
  frame_interval: 5
  max_frames: -1
  binary_cls: true
  num_workers: 4
  dim_state: 128
  dim_action: 3
  score_thresh: 0.7
  use_salmap: False  # set to False to speedup data loading
  use_foveation: True
  env_model: ./output/saliency/checkpoints/saliency_model_25.pth
SAC:
  gamma: 0.99
  tau: 1.0
  lr: 0.0003
  num_classes: 2
  hidden_size: 256
  policy: "Deterministic"
  target_update_interval: 1000
  automatic_entropy_tuning: True
  alpha: 0.001
  beta: 0.01
  replay_size: 1000000
  batch_size: 512
  updates_per_step: 4
  logging_interval: 100
  policy_weight_decay: 0.001
