ENV:
  dataset: DAD
  data_path: ./data/DAD
  batch_size: 4
  image_shape: [360, 640]
  input_shape: [480, 640]
  frame_interval: 4
  step_size: 1
  len_clip: 1
  score_thresh: 0.5
  state_norm: true
  saliency: 'MLNet'
  env_model: ./models/saliency/mlnet_25.pth
SAC:
  gamma: 0.99
  tau: 0.005
  lr: 0.0003
  lr_alpha: 0.00005
  num_classes: 2
  hidden_size: 64
  dim_state: 128
  dim_action: 1
  type_acc: "Gaussian"
  actor_update_interval: 2
  target_update_interval: 1
  automatic_entropy_tuning: true
  alpha: 0.001
  beta_accident: 1.0
  replay_size: 1000000
  batch_size: 64
  updates_per_step: 4
  logging_interval: 100
  weight_decay: 0.00001
  arch_type: "rae"  # mlp or rae
  dim_latent: 64    # only useful when rae
  latent_lambda: 0.0001
  gpu_replay: true
