ENV:
  data_path: ./data/DADA-2000
  batch_size: 1
  image_shape: [660, 1584]
  input_shape: [480, 640]
  frame_interval: 1
  step_size: 4
  len_clip: 16
  max_frames: 600  # 20 seconds
  binary_cls: true
  num_workers: 0
  dim_state: 384
  dim_action: 3
  score_thresh: 0.7
  use_salmap: false  # set to False to speedup data loading
  use_foveation: true
  state_norm: false
  saliency: 'TASED-Net'
  env_model: ./models/saliency/tasednet_iter_1000.pt
SAC:
  gamma: 0.99
  tau: 0.005
  lr: 0.0003
  num_classes: 2
  hidden_size: 64
  policy: "Gaussian"
  target_update_interval: 1000
  automatic_entropy_tuning: true
  alpha: 0.001
  beta_actor: 0.01
  beta_fix: 1.0
  replay_size: 1000000
  batch_size: 256
  updates_per_step: 4
  logging_interval: 100
  policy_weight_decay: 0.001
